### ISSUE TITLE
Display in fullscreen not ideal

### ISSUE THREAD

**Issue by ouryperd** [IJMacD/newsmap-js#34]
Great app. I'm using the app in a browser (latest FF) on a wall-mounted PC in fullscreen mode. There are two issues with the display:

1) Text is cut off in some cases.
2) When attempting to move the mouse curor to the edge of the screen, no matter where, it rests on an item and displays the source (see bottom right corner: TimesLIVE).

![newsmap](https://user-images.githubusercontent.com/29674819/130102559-d01ee846-2470-4209-93f1-ae9306b54b48.png)

**Comment by IJMacD** [comment]
Sorry it's been over a year since you opened this issue. I've recently been working on the project so I've been trying to get round to some old issues.

I've added 1px at the top and bottom of the screen when in fullscreen mode to give somewhere to rest the mouse without triggering the link source etc.

Let me know if it works for you.

The text sizing is a difficult problem I'll try to tackle separately.

**Comment by ouryperd** [comment]
Hi, yes it's good thanks. I will close this one. Thank you.
