### ISSUE TITLE
Heroku App not working

### ISSUE THREAD

**Issue by seedrickMCWW** [IJMacD/newsmap-js#42]
Console is saying some stuff about cross-origin and not being able to reach `analytics.js`. Haven't had time to dig/troubleshoot much but it seems this is happening from any browser/internet connection.

**Comment by IJMacD** [comment]
Hey thanks for raising this issue. I'm currently in the process of moving infrastructure due to Heroku discontinuing their free tier.

Previously:

    https://newsmap.ijmacd.com -> https://newsmap-js.herokuapp.com

New:

    https://newsmap.ijmacd.com -> https://newsmap-js.azurewebsites.net

Unfortunately it seems the switch didn't go smoothly because of service workers still serving the old site in browsers rather than redirecting to the new infrastructure.

I'll try to push a change that disables the service worker which will hopefully catch most users before the free tier disappears completely.

In the meantime, a hard refresh (Ctrl-Shift-R) in your browser should redirect you correctly.

**Comment by seedrickMCWW** [comment]
Redirect works! But now there's a CORS issue, just an FYI.

**Comment by IJMacD** [comment]
Thanks again for reporting!

As you can see I've been having some teething troubles.

The new backend went down because I'd hit the quotas already. It should be
back up for now but I'll monitor in the meantime.

Thanks,
Iain

**Comment by seedrickMCWW** [comment]
Thanks!

**Comment by z-x-x136** [comment]
I landed https://newsmap-js.azurewebsites.net ,There's no news right now.

**Comment by IJMacD** [comment]
Works correctly if you use the canonical URL: https://newsmap.ijmacd.com

It worked before and after the migration to the new cloud provider.

(Let me know if it doesn't)
