### ISSUE TITLE
Missing SPAIN from the drop down list of countries

### ISSUE THREAD

**Issue by levagency** [IJMacD/newsmap-js#6]
Missing SPAIN from the drop down list of countries

**Comment by IJMacD** [comment]
Hi levagency,

Thanks for bringing this up. However, Google News hasn't been available in Spain since 2014.

You can check out this blog post: https://europe.googleblog.com/2014/12/an-update-on-google-news-in-spain.html
Or these news articles from the time:
* https://www.theguardian.com/technology/2014/dec/11/google-news-spain-to-close-in-response-to-tax-on-story-links
* https://www.theverge.com/2014/12/11/7375733/google-news-spain-shutdown
* https://www.eff.org/deeplinks/2014/12/google-news-shuts-shop-spain-thanks-ancillary-copyright-law

**Comment by levagency** [comment]
Hey, I appreciate such an expanded answer/explanation.
       I guess they enjoy shooting themselves in the foot, just like sending THOUSANDS of Spanish Children to the USSR - during the Spanish Civil War - most of them would never be returned home.
   I just want to throw my hands up in the air and shrug the shoulders - ohh the "STUPIDITY"!!!
Thank you again for a very extensive response.
